### ISSUE TITLE
Download fails for citations with an `@` symbol

### ISSUE THREAD

**Issue by svenkeidel** [cr-marcstevens/dblpbibtex#11]
Hi Marc, this is an awesome project, I love it!

I ran into an issue when I tried to cite a proceedings paper with an `@` symbol in the book title (https://dblp.uni-trier.de/rec/bibtex/conf/icfp/HamanaF11). When I ran the `dblpbibtex` tool, it downloads the citation up until the `@` symbol then stops:
```
@inproceedings{DBLP:conf/icfp/HamanaF11,
  author    = {Makoto Hamana and
               Marcelo P. Fiore},
  title     = {A foundation for GADTs and inductive families: dependent polynomial
               functor approach},
  booktitle = {Proceedings of the seventh {ACM} {SIGPLAN} workshop on Generic programming,
               WGP
@inproceedings{DBLP:conf/fpca/Wadler89,
...
```
I tested this with the tagged version 2.1.

**Comment by cr-marcstevens** [comment]
Hi Sven, that seems quite logical as it assumes a new bibitem starts at `@`. I'll have a look and see if I can achieve a better behaviour for DBLP.

**Comment by svenkeidel** [comment]
Great, thank you for taking a look. Let me know if I can help.

**Comment by cr-marcstevens** [comment]
This issue should now be solved, thanks for reporting it!

**Comment by svenkeidel** [comment]
Wow this was fast. Thank you for fixing this. I will test this right away.

**Comment by svenkeidel** [comment]
Yes, this fixed it. Thanks again :+1:
