### ISSUE TITLE
dblpbibtex does not load cross refrences for some citation

### ISSUE THREAD

**Issue by svenkeidel** [cr-marcstevens/dblpbibtex#13]
Hi Marc, keep up the good work :+1: 

`dblpbibtex` does not download the cross reference `DBLP:conf/popl/79` for this citation (https://dblp.uni-trier.de/rec/bibtex2/conf/popl/CousotC79). I deleted the corresponding block from the bib file and ran `dblpbibtex` again, but same outcome. Here is the complete [log](https://github.com/cr-marcstevens/dblpbibtex/files/4687786/log.txt) of this rerun.

I don't know what makes this citation special, since it works for all other citations in my document. I assume it might be another issue with the parser (the issue existed already before https://github.com/cr-marcstevens/dblpbibtex/issues/11). Any ideas?

**Comment by cr-marcstevens** [comment]
I have tested it and here it works fine.
```
DBLPBibTeX - version 2.2 - Copyright Marc Stevens 2010-2019
Projectpage: https://github.com/cr-marcstevens/dblpbibtex/
Cannot find configuration file 'dblpbibtex.cfg' in directories './' and '/home/stevens/'.
Parsing auxfile: 'test.aux'.
Configuration:
    bibtex: 'bibtex'
    mainbibfile: defaults to first found bib file
    DBLP format: crossref
Bib files: 'test.bib'
Bib search directories: '.'
Loaded content of main bibfile: 'test.bib'!
New citation: 'DBLP:conf/popl/CousotC79'
Downloaded bibtex entry:
@inproceedings{DBLP:conf/popl/CousotC79,
  author    = {Patrick Cousot and
               Radhia Cousot},
  title     = {Systematic Design of Program Analysis Frameworks},
  booktitle = {Conference Record of the Sixth Annual {ACM} Symposium on Principles
               of Programming Languages, San Antonio, Texas, USA, January 1979},
  pages     = {269--282},
  year      = {1979},
  crossref  = {DBLP:conf/popl/79},
  url       = {https://doi.org/10.1145/567752.567778},
  doi       = {10.1145/567752.567778},
  timestamp = {Tue, 06 Nov 2018 11:07:43 +0100},
  biburl    = {https://dblp.org/rec/conf/popl/CousotC79.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}                                                                                                                                                                                                                                                                                                    Saved new content of main bibfile: 'test.bib'!
Loaded content of main bibfile: 'test.bib'!
(NEW) crossref: 'DBLP:conf/popl/79'
New crossref: 'DBLP:conf/popl/79'
Downloaded bibtex entry:
@proceedings{DBLP:conf/popl/79,
  editor    = {Alfred V. Aho and
               Stephen N. Zilles and
               Barry K. Rosen},
  title     = {Conference Record of the Sixth Annual {ACM} Symposium on Principles
               of Programming Languages, San Antonio, Texas, USA, January 1979},
  publisher = {{ACM} Press},
  year      = {1979},
  url       = {http://dl.acm.org/citation.cfm?id=567752},
  timestamp = {Mon, 21 May 2012 16:19:51 +0200},
  biburl    = {https://dblp.org/rec/conf/popl/79.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}
Saved new content of main bibfile: 'test.bib'!
Loaded content of main bibfile: 'test.bib'!
No updates to save to main bibfile: 'test.bib'!
```

This is running pdflatex and dblpbibtex on the following test.tex file:
```
\documentclass{article}
\usepackage{url}
\begin{document}
\cite{dblpbibtex:dblpformat:crossref}
\cite{DBLP:conf/popl/CousotC79}
\bibliographystyle{plain}
\bibliography{test}
\end{document}
```

**Comment by cr-marcstevens** [comment]
Does `DBLP:conf/popl/79` or `dblp:conf/popl/79` already exist in the `.bib` file?

**Comment by svenkeidel** [comment]
Weird, your minimal example also works for me.

No, DBLP:conf/popl/79 or dblp:conf/popl/79 are not referenced anywhere else. Here is the complete [bib file](https://github.com/cr-marcstevens/dblpbibtex/files/4687887/dblp.txt) that `dblpbibtex` generates.

**Comment by svenkeidel** [comment]
Here is a minimal example with all references in my document that actually works.
```
\documentclass{article}
\usepackage{url}
\begin{document}
\cite{dblpbibtex:dblpformat:crossref}
\cite{DBLP:conf/popl/CousotC79}
\cite{DBLP:journals/scp/Hughes00}
\cite{DBLP:journals/logcom/CousotC92}
\cite{DBLP:journals/iandc/Moggi91}
\cite{DBLP:conf/popl/LiangHJ95}
\cite{DBLP:conf/popl/CousotC02}
\cite{DBLP:conf/nato/Wadler92}
\cite{DBLP:conf/ifip/Reynolds83}
\cite{DBLP:conf/icfp/VisserBT98}
\cite{DBLP:conf/icfp/Paterson01}
\cite{DBLP:conf/icfp/HamanaF11}
\cite{DBLP:conf/fpca/Wadler89}
\cite{DBLP:conf/colog/CoquandP88}
\cite{DBLP:books/daglib/0098888}
\bibliographystyle{plain}
\bibliography{test}
\end{document}
```

**Comment by svenkeidel** [comment]
Aha :bulb: I have two reference files, `references.bib` in which I keep my hand-written references and `dblp.bib` which `dblpbibtex` generates. The file `references.bib` already has an entry for `DBLP:conf/popl/79`, so `dblpbibtex` does not download it when it generates `dblp.bib`.

**Comment by cr-marcstevens** [comment]
Happy that you've found the cause, does that mean I can close this issue?

**Comment by svenkeidel** [comment]
Maybe we can improve the user experience in such a case.

Redownloading the cross reference and adding it to the generate bib file fixes the `bibtex` error. Currently `dblpbibtex` does not do that because the reference already exists in another user provided bib file.

What do you think?

**Comment by cr-marcstevens** [comment]
Not sure how dblpbibtex can help there.

Why is `bibtex` even throwing an error if the crossref exists in one of the .bib files?

**Comment by svenkeidel** [comment]
Here is a minimal example that illustrates this issue:
```
\documentclass{article}
\usepackage{url}
\begin{document}
\cite{dblpbibtex:dblpformat:crossref}
\cite{dblpbibtex:mainbibfile:dblp.bib}
\cite{DBLP:conf/popl/CousotC79}

% This file contains hand-written references and other references copied by hand from DBLP 
\begin{filecontents}{references.bib}
@proceedings{DBLP:conf/popl/79,
  editor    = {Alfred V. Aho and
               Stephen N. Zilles and
               Barry K. Rosen},
  title     = {Conference Record of the Sixth Annual {ACM} Symposium on Principles
               of Programming Languages, San Antonio, Texas, USA, January 1979},
  publisher = {{ACM} Press},
  year      = {1979},
  url       = {http://dl.acm.org/citation.cfm?id=567752},
}
\end{filecontents} 

\bibliographystyle{plain}
\bibliography{references, dblp}

\end{document}
```

Log of `dblpbibtex test`:
```
DBLPBibTeX - version 2.2 - Copyright Marc Stevens 2010-2019
Projectpage: https://github.com/cr-marcstevens/dblpbibtex/
Cannot find configuration file 'dblpbibtex.cfg' in directories './' and '/home/sven/'.
Parsing auxfile: 'test.aux'.
Configuration:
	bibtex: '/nix/store/s1336dw4p8d3xlwwyblp9wqxy6j6saw2-texlive-combined-small-2019/bin/bibtex'
	mainbibfile: 'dblp.bib'
	DBLP format: crossref
Bib files: 'references.bib' 'dblp.bib'
Bib search directories: '.'
Loaded content of main bibfile: 'dblp.bib'!
New citation: 'DBLP:conf/popl/CousotC79'
Downloaded bibtex entry:
@inproceedings{DBLP:conf/popl/CousotC79,
  author    = {Patrick Cousot and
               Radhia Cousot},
  title     = {Systematic Design of Program Analysis Frameworks},
  booktitle = {Conference Record of the Sixth Annual {ACM} Symposium on Principles
               of Programming Languages, San Antonio, Texas, USA, January 1979},
  pages     = {269--282},
  year      = {1979},
  crossref  = {DBLP:conf/popl/79},
  url       = {https://doi.org/10.1145/567752.567778},
  doi       = {10.1145/567752.567778},
  timestamp = {Tue, 06 Nov 2018 11:07:43 +0100},
  biburl    = {https://dblp.org/rec/conf/popl/CousotC79.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}
Saved new content of main bibfile: 'dblp.bib'!
Loaded content of main bibfile: 'dblp.bib'!
No updates to save to main bibfile: 'dblp.bib'!
Running bibtex: '/nix/store/s1336dw4p8d3xlwwyblp9wqxy6j6saw2-texlive-combined-small-2019/bin/bibtex "test"'.
This is BibTeX, Version 0.99d (TeX Live 2019/NixOS.org)
The top-level auxiliary file: test.aux
The style file: plain.bst
Database file #1: references.bib
Database file #2: dblp.bib
A bad cross reference---entry "DBLP:conf/popl/CousotC79"
refers to entry "DBLP:conf/popl/79", which doesn't exist
Warning--I didn't find a database entry for "dblpbibtex:dblpformat:crossref"
Warning--I didn't find a database entry for "dblpbibtex:mainbibfile:dblp.bib"
Warning--I didn't find a database entry for "DBLP:conf/popl/79"
(There was 1 error message)
```

**Comment by svenkeidel** [comment]
There are at least three ways of fixing this:
1. The user adds `DBLP:conf/popl/79` manually to `dblb.bib`
2. `dblpbibtex` downloads `DBLP:conf/popl/79` and adds it to `dblb.bib`
2. Manually change the order of bib files: `\bibliography{dblp, references}`

**Comment by cr-marcstevens** [comment]
Thanks, but this really remains a bibtex issue: all crossrefs should appear later than the bibentries that use them.
Re fixing it:
1. this is the suggested fix: keep all DBLP entries in dblp.bib. Don't manually add DBLP entries in other bib files.
2. I don't think placing the crossref again in dblp.bib solves it, wouldn't bibtex complain about a bib entry occuring twice?
3. although reordering may help in this case, what if dblpbibtex spots a crossref in `references,bib`. Then it will put the crossref (if it can download it) in `dblp.bib` and will also cause a bibtex error.

**Comment by svenkeidel** [comment]
I understand. Thanks for the explanation.

> this is the suggested fix: keep all DBLP entries in dblp.bib. Don't manually add DBLP entries in other bib files.

Yes, this sounds sensible. Maybe you can add a warning about this to the readme to keep other users from running into the same mistake?

> I don't think placing the crossref again in dblp.bib solves it, wouldn't bibtex complain about a bib entry occuring twice?

I tried this and it actually works. I don't know why bibtex does not complain about the duplicate when it is in different bib files.

Feel free to close this issue.

**Comment by svenkeidel** [comment]
I think I figured out how bibtex picks a reference when there are duplicates.
- Duplicates in the same file cause an error
- If there are duplicates in multiple bib files, bibtex picks the reference in the first file

Anyways, this problem can be fixed by reordering the bib files and no changes to dblpbibtex are necessary. I'm closing this now.

**Comment by svenkeidel** [comment]
Thanks for your help.
