### ISSUE TITLE
dblpbibtex does not download new citation

### ISSUE THREAD

**Issue by svenkeidel** [cr-marcstevens/dblpbibtex#14]
Hi Marc,

I ran into a new issue where dblpbibtex suddenly stopped downloading new citations:
```
DBLPBibTeX - version 2.2 - Copyright Marc Stevens 2010-2019
Projectpage: https://github.com/cr-marcstevens/dblpbibtex/
Loading configuration from: dblpbibtex.cfg
Parsing auxfile: [...]
Configuration:
	bibtex: '/nix/store/s1336dw4p8d3xlwwyblp9wqxy6j6saw2-texlive-combined-small-2019/bin/bibtex'
	mainbibfile: 'dblp.bib'
	DBLP format: crossref
Bib files: 'dblp.bib' 'references.bib'
Bib search directories: '.'
Loaded content of main bibfile: 'dblp.bib'!
New citation: 'DBLP:conf/aplas/ChenMC08'
New citation: 'DBLP:conf/icfp/Asada10'
New citation: 'DBLP:conf/scam/StievenartVMR16'
New citation: 'DBLP:journals/corr/CortesiCF13'
New citation: 'DBLP:journals/jfp/JacobsHH09'
New citation: 'DBLP:journals/pacmpl/BodinGJS19'
No updates to save to main bibfile: 'dblp.bib'!
```
Here is the contents of the complete [dblp.bib](https://github.com/cr-marcstevens/dblpbibtex/files/5244557/dblp.txt) file. Any idea what is going wrong? Thanks in advance.

Regards,
Sven

**Comment by cr-marcstevens** [comment]
Thanks for noticing!

It appears DBLP has changed their URL scheme: 

https://blog.dblp.org/2020/08/18/new-dblp-url-scheme-and-api-changes/

**Comment by svenkeidel** [comment]
Thanks for the quick reply!

So what does this mean? Can this be fixed with a dblpbibtex update, or do users have to take action and change URLs according to the new scheme?

**Comment by cr-marcstevens** [comment]
I think I have it fixed, but I still need to create a new release. Will be soon.

**Comment by svenkeidel** [comment]
Awesome, thanks for the great support Marc! I'll leave it up to you to close this issue.

**Comment by cr-marcstevens** [comment]
👍👍 new release is out

**Comment by svenkeidel** [comment]
I just tested the new release. Works like a charm. Thanks again!
