### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by disteph** [cr-marcstevens/dblpbibtex#9]
This is an amazing tool! But I am in a project that requires bibtex entries (don't ask why) to be exactly those of the "standard mode" of dblp rather than the "with crossref mode". At the moment, dblpbibtex downloads the "with crossref mode" and this is hard-wired in the code, namely:
```
bib_get.hpp:	auto hdr_html = url_get("https://dblp.org/rec/bib2/" + key.substr(5));
```
In order to get the "standard mode" entries, one needs to use `https://dblp.org/rec/bib1/` (and `https://dblp.org/rec/bib0/` gives the "condensed mode". For the sake of my project, I changed `bib2` to `bib1` in your code and recompiled dblpbibtex, but the clean way to do it would be to have a dblpbibtex option to select between the three formats. Would it be something you'd consider?

**Comment by cr-marcstevens** [comment]
Thanks for the feature request!
I was actually not aware of this dblp feature, I thought bib2 was the one and only option.

It should be easy adding an option to control this.

**Comment by cr-marcstevens** [comment]
Can you checkout branch 'feature-dblpformat'?

**Comment by cr-marcstevens** [comment]
Fulfilled.

**Comment by disteph** [comment]
Wow, this was the quickest feature request realization I have ever seen.
It works like a charm, thanks!
